In [1]:
import numpy as np
import nn

# Implementing a simple convolution
For the first part of the exercise you should try to get a feel for what a convolution and a dimensionality reduction (pooling does). We will always assume that we want zero padding around the input tensor (e.g. a "same" convolution).

First off implement convolution in a simple function that takes an input tensor X convolves it with some filters (later the weights of a neural network) and writes the output into convout. Creating input and output of the correct size is later already partially handeled for you in the network code (have a look at nn/conv/layers.py).

In [8]:
# the following uses tha matrix multiplication convolution
# which we will use in the next exercises
from nn.conv.conv_op import forward_conv
def conv(image,filters,convout):
    pad = 1
    out, _ = forward_conv(image,filters, 1, pad)
    np.copyto(convout, out)
    return convout

# if you comment in this instead you get something that
# is a simple loop based convolution. Note that this is not fully featured
# I included it mainly to help you debug your code 
# (as I suspect most of you implemented convolutions this way)
"""
from conv_classic import forward_conv
def conv(image,filters,convout):
   forward_conv(image, filters, convout)
   return convout
"""

'\nfrom conv_classic import forward_conv\ndef conv(image,filters,convout):\n   forward_conv(image, filters, convout)\n   return convout\n'

Once you implemented the above we can let it work on a simple minimal example of a (4,4) image with one channel.

In [9]:
img = np.asarray([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]], dtype=np.float64).reshape(1,1,4,4)
# remember the first dimension is the batch size here
# lets repeat the image so that we get a more useful test
imgs = np.repeat(img,2 , axis=0)
print(imgs.shape)

(2, 1, 4, 4)


In [10]:
# to test we will only use one (3,3) filter which does not fits into the (4,4) images so you need to do padding ;)
# first dimension is input channels, second is the number of filters 3rd and 4th are filter dimensions
filters = np.eye(3).reshape((1,1,3,3))
print(filters.shape)

(1, 1, 3, 3)


In [11]:
# since we are doing same convolutions the output should be the same size as the input
convout = np.zeros_like(imgs)

In [12]:
# apply the convolution
conv(imgs, filters, convout)

array([[[[  7.,   9.,  11.,   4.],
         [ 15.,  18.,  21.,  11.],
         [ 23.,  30.,  33.,  19.],
         [ 13.,  23.,  25.,  27.]]],


       [[[  7.,   9.,  11.,   4.],
         [ 15.,  18.,  21.,  11.],
         [ 23.,  30.,  33.,  19.],
         [ 13.,  23.,  25.,  27.]]]])

In [13]:
# print the output and compare to the desired output
print(convout)

[[[[  7.   9.  11.   4.]
   [ 15.  18.  21.  11.]
   [ 23.  30.  33.  19.]
   [ 13.  23.  25.  27.]]]


 [[[  7.   9.  11.   4.]
   [ 15.  18.  21.  11.]
   [ 23.  30.  33.  19.]
   [ 13.  23.  25.  27.]]]]


In [14]:
real_output = np.asarray(
[[[[  7.,   9.,  11.,   4.],
   [ 15.,  18.,  21.,  11.],
   [ 23.,  30.,  33.,  19.],
   [ 13.,  23.,  25.,  27.]]],


 [[[  7.,   9.,  11.,   4.],
   [ 15.,  18.,  21.,  11.],
   [ 23.,  30.,  33.,  19.],
   [ 13.,  23.,  25.,  27.],]]], dtype=np.float64)

In [15]:
diff = np.linalg.norm(real_output-convout)
# the difference between those should be smaller than eps
eps = 1e-4
print("Diff {}".format(diff))
assert(diff < eps)

Diff 0.0
