In [1]:
import numpy as np
import nn

# Implementing a simple convolution
For the first part of the exercise you should try to get a feel for what a convolution and a dimensionality reduction (pooling does). We will always assume that we want zero padding around the input tensor (e.g. a "same" convolution).

First off implement convolution in a simple function that takes an input tensor X convolves it with some filters (later the weights of a neural network) and writes the output into convout. Creating input and output of the correct size is later already partially handeled for you in the network code (have a look at nn/conv/layers.py).

In [2]:
def conv(image,filters,convout):
    # TODO: implement convolution here
    pass

Once you implemented the above we can let it work on a simple minimal example of a (4,4) image with one channel.

In [36]:
img = np.asarray([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]], dtype=np.float64).reshape(1,1,4,4)
# remember the first dimension is the batch size here
# lets repeat the image so that we get a more useful test
imgs = np.repeat(img,2 , axis=0)
print(imgs.shape)

(2, 1, 4, 4)


In [44]:
# to test we will only use one (3,3) filter which does not fits into the (4,4) images so you need to do padding ;)
# first dimension is input channels, second is the number of filters 3rd and 4th are filter dimensions
filters = np.eye(3).reshape((1,1,3,3))
print(filters.shape)

(1, 1, 3, 3)


In [45]:
# since we are doing same convolutions the output should be the same size as the input
convout = np.zeros_like(imgs)

In [52]:
# apply the convolution
conv(imgs, filters, convout)

In [47]:
# print the output and compare to the desired output
print(convout)

[[[[  7.   9.  11.   4.]
   [ 15.  18.  21.  11.]
   [ 23.  30.  33.  19.]
   [ 13.  23.  25.  27.]]]


 [[[  7.   9.  11.   4.]
   [ 15.  18.  21.  11.]
   [ 23.  30.  33.  19.]
   [ 13.  23.  25.  27.]]]]


In [49]:
real_output = np.asarray(
[[[[  7.,   9.,  11.,   4.],
   [ 15.,  18.,  21.,  11.],
   [ 23.,  30.,  33.,  19.],
   [ 13.,  23.,  25.,  27.]]],


 [[[  7.,   9.,  11.,   4.],
   [ 15.,  18.,  21.,  11.],
   [ 23.,  30.,  33.,  19.],
   [ 13.,  23.,  25.,  27.],]]], dtype=np.float64)

In [51]:
diff = np.linalg.norm(real_output-convout)
# the difference between those should be smaller than eps
eps = 1e-4
print("Diff {}".format(diff))
assert(diff < eps)

Diff 0.0
